sudo: false
language: ruby
cache: bundler
bundler_args: --without development
rvm:
  - 2.5.8
  - 2.6.6
  - 2.7.1
  - jruby-9.2.12.0
  - jruby-9.1.17.0
  - ruby-head
  - jruby-head
  - rbx-5.0
  - rbx-4.20
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-2.11
    - rvm: rbx-3.14
script:
  - bundle exec rspec
