sudo: false
language: ruby
cache: bundler
bundler_args: --without development
rvm:
  - 2.0.0
  - 2.1.8
  - 2.2.4
  - 2.3.0
  - 2.4.0
  - jruby-9.0.5.0
  - ruby-head
  - jruby-head
  - rbx-2.11
  - rbx-3.14
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-2.11
    - rvm: rbx-3.14
script:
  - bundle exec rspec
