language: ruby
cache: bundler
env: JRUBY_OPTS=--2.0
rvm:
  - 2.0.0
  - jruby-1.7.9
  - ruby-head
  - jruby-head
  - rbx-2.2.1
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-2.2.1
script:
  - rake spec
